version: '3'
services:
  mr_purchase_request_db:
    image: mariadb:10.7
    ports:
      - 3312:3306
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mr_purchase_request_db
      - MARIADB_USER=mobility
      - MARIADB_PASSWORD=root
    volumes:
      - mr_purchase_request_db:/var/lib/mysql
    networks:
      - mobility

  mr_purchase_request_cache:
    image: redis:7.0.0-alpine
    restart: always
    ports:
      - 6380:6379
    command: redis-server --requirepass root
    volumes:
      - mr_purchase_request_cache:/data

volumes:
  mr_purchase_request_db:
  mr_purchase_request_cache:
networks:
  mobility:
    name: mobility
